Added Generator
craft-ai/craft-ai-starterkit-nodejs pull request #25
Opened 2021-02-11 14:17 UTC by yassineSaid-craft

2021-02-18 10:28 UTC, Giska requested changes
Don't forget the changelog

2021-02-18 10:28 UTC, Giska commented on src/main.js
> +          .then((data_1) => JSON.parse(data_1))
You should create a function that read a file and return json data

2021-02-18 10:28 UTC, Giska commented on src/main.js
> +                  })
```suggestion
                  .then(() =>CRAFT_CLIENT.deleteGenerator(GENERATOR_NAME))
```

2021-02-18 10:28 UTC, Giska commented on src/main.js
> +      })
Why deleting the generator here ?

2021-02-18 10:28 UTC, Giska commented on src/main.js
> +            };
Since the configuration is the same for each agents, I don't think that you need to create a variable for each

2021-02-18 10:28 UTC, Giska commented on src/main.js
> +                          stateChange: originalData.context.light == "ON" ? (originalData.context.movement > 1 ? 'both' : 'light') : (originalData.context.movement > 1 ? 'movement' : 'none'),
Set a function that does the transformation

2021-02-18 10:34 UTC, yassineSaid-craft commented on src/main.js
> +      })
I thought that the generator's name can't be duplicate

2021-02-18 10:35 UTC, yassineSaid-craft commented
> Don't forget the changelog

Should I add a new changelog?

2021-02-18 10:42 UTC, Giska commented on src/main.js
> +      })
yes but you are deleting it also later no ?

2021-02-18 13:28 UTC, Giska requested changes

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +      })
```suggestion
```
Remove that deletion is done after

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +        }
```suggestion
        const d1 = craftai.interpreter.decide(
          tree,
          {
            movement: 0
          },
          new craftai.Time('2010-01-04T01:30:00+09:00')
        );
        console.log(`Decision taken:\n- The light is ${d1.output.light.predicted_value} when there is no movement at 1:30AM.`);
```

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +        }
```suggestion
        const d2 = craftai.interpreter.decide(
          tree,
          {
            movement: 0
          },
          new craftai.Time('2010-01-04T08:58:00+09:00')
        );
        console.log(`- The light is ${d2.output.light.predicted_value} when there is no movement at 8:58AM.`);
```

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +        }
```suggestion
        const d3 = craftai.interpreter.decide(
          tree,
          {
            movement: 0
          },
          new craftai.Time('2010-01-04T09:42:00+09:00')
        );
        console.log(`- The light is ${d3.output.light.predicted_value} when there is no movement at 9:42AM.`);
```

2021-02-18 13:28 UTC, Giska commented on src/main.js
>          }
```suggestion
        const d4 = craftai.interpreter.decide(
          tree,
          {
            movement: 2
          },
          new craftai.Time('2010-01-04T09:42:00+09:00')
        );
        console.log(`- The light is ${d4.output.light.predicted_value} when there is some movement at 9:42AM.`);
```

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +        return CRAFT_CLIENT.deleteAgentBulk(deleteBulkPayload);
```suggestion
        return Promise.all([
          CRAFT_CLIENT.deleteAgentBulk(deleteBulkPayload),
          CRAFT_CLIENT.deleteGenerator(GENERATOR_NAME)
        ]);
```

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +        operations_agent_3 = utils.prepareData(context_3, ROOM3);
```suggestion
      .then(() => Promise.all([
        utils.readData(LOCAL_FILE_PATH1)),
        utils.readData(LOCAL_FILE_PATH2),
        utils.readData(LOCAL_FILE_PATH3)
      ])
      .then(([context1, context2, context3]) => {
        const operations_agent_1 = utils.prepareData(context_1, ROOM1);
        const operations_agent_2 = utils.prepareData(context_2, ROOM2);
        const operations_agent_3 = utils.prepareData(context_3, ROOM3);
```

2021-02-18 13:28 UTC, Giska commented on src/utils.js
> +var readData = async function (path) {
```suggestion
const readData = async (path) => {
```

2021-02-18 13:28 UTC, Giska commented on src/utils.js
> +}
```suggestion
  return new Promise((resolve, reject) => fs.readFile(path, (err, data) => {
    if (err) {
      reject(err);
    }
    resolve(data);
  }))
    .then((data) => JSON.parse(data))
    .then((context) => {
      return context;
     })
     .catch((error) => {
       console.log('Error!', error);
       process.exit(1);
     });
}
```
Take care of the lint part. We used space instead of tab and a "tab" is two spaces. You can run `npm run lint` to check this

2021-02-18 13:28 UTC, Giska commented on src/utils.js
> +}
```suggestion
const prepareData = (context, room) => {
  let operationsAgent = [];
  context.forEach((originalData) => {
    data = {
      timestamp: originalData.timestamp,
      context: {
        stateChange: originalData.context.light == "ON" ? (originalData.context.movement > 1 ? 'both' : 'light') : (originalData.context.movement > 1 ? 'movement' : 'none'),
        room: room,
        tz: originalData.context.tz,
        movement: originalData.context.movement
      }
    }
    operationsAgent.push(data);
  });
  return operationsAgent;
}

```

2021-02-18 13:28 UTC, Giska commented on src/utils.js
> +exports.prepareData = prepareData;
```suggestion
module.exports = {
  readData,
  prepareData
};
```

2021-02-18 13:28 UTC, Giska commented on src/main.js
> +        }
You should prefere to declare a new variable for the decision instead of declaring it inside a new block

2021-02-19 14:12 UTC, Giska requested changes

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
> +        }
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
>          {
```suggestion
```

2021-02-19 14:12 UTC, Giska commented on src/main.js
> +        }
```suggestion
```

2021-02-19 14:53 UTC, Giska approved these changes

2021-02-19 14:53 UTC, merged